### ISSUE TITLE
No module named 'mypy_extensions'

### ISSUE THREAD

**Issue by ranyxr** [neulab/lrlm#1]
Hi,
When I ran `python run.py`, got this error
```
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from models import AliasLM, LRLM, NKLM, VanillaLM
  File "/content/lrlm/models/__init__.py", line 2, in <module>
    from models.lrlm import *
  File "/content/lrlm/models/lrlm.py", line 7, in <module>
    from mypy_extensions import TypedDict
ModuleNotFoundError: No module named 'mypy_extensions'
```

**Comment by rooa** [comment]
Hi, thanks for pointing out! The requirements file was not complete. Please install the module:

```pip install mypy-extensions```

 We will update the requirements file.
